on: [push, pull_request]
name: Linux
strategy:
  fail-fast: false

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        perl: [ '5.32', '5.30', '5.26', '5.22', '5.16', '5.8' ]
    name: Perl ${{ matrix.perl }}
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: switch to perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: run tests
        env:
          PERL_USE_UNSAFE_INC: 0
        run: |
            perl -v
            cpanm --quiet --notest --installdeps .
            perl Makefile.PL
            make test
