on: [push, pull_request]
name: Linux

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false   
      max-parallel: 6
      matrix:
        perl: [ '5.34','5.32', '5.30', '5.26', '5.22', '5.16' ]
    name: Perl ${{ matrix.perl }}
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: switch to perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: run tests
        env:
          PERL_USE_UNSAFE_INC: 0
        run: |
            perl -v
            cat cpanfile
#            cpanm --force --quiet --notest Moo
            cpanm --force --verbose DateTime
#            cpanm --force --quiet --notest --installdeps .
#            perl Makefile.PL
#            make test
